# Run with $ bundle exec jekyll serve

title: Marta & Ethan
email: your-email@domain.com
description: > # ignore newlines until "baseurl:"
  Site for Marta and Ethans wedding
baseurl: "/wedding-site"
url: "https://esoergel.github.io/"
background: "img/IMG_20000409_242006184_HDR.jpg"
github_username:  esoergel
gems:
  - github-pages

# Build settings
markdown: kramdown
lsi: false
safe: true
source: "."
incremental: false
highlighter: rouge
gist:
  noscript: false
